name: khmer_american_school_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  responsive_sizer: ^3.3.1

dev_dependencies:
  flutter_launcher_icons: "^0.14.4"
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/ic_foreground.png"
  adaptive_icon_background: "assets/icons/ic_background.png" # Can be a color like "#ffffff"
  adaptive_icon_foreground: "assets/icons/ic_foreground.png"
  adaptive_icon_monochrome: "assets/icons/ic_monochrome.png" # For Android 13+ themed icons
flutter:

  uses-material-design: true

  assets:
    - assets/icons/ic_foreground.png
    - assets/icons/ic_background.png
    - assets/icons/ic_monochrome.png